services:
  - type: web
    name: DataLens
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: "8000"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLEXSRFPROTECTION
        value: "false"
      - key: STREAMLIT_LOGGER_LEVEL
        value: "error"
